### ISSUE TITLE
detect.py

### ISSUE THREAD

**Issue by bbartling** [DoganK01/YOLOV7-OBJECT-COUNTER-V1.2#1]
On the arg `classes` if I am just after people only, would it make my platform run faster? Its a bit lagy but it works really well just curious if it would speed things up at all?

![image](https://user-images.githubusercontent.com/29737117/190244098-80479b42-b2b8-48c0-a3f6-171fbc8da80e.png)

**Comment by DoganK01** [comment]
Sorry, but I didn't make the yolo model. This is about yolo, not me. But I can delete bounding boxes if you want (if you think it looks bad).

**Comment by DoganK01** [comment]
Also, make sure the model see all of them(people). I mean the whole person. Because the model was made according to coordinate comparison. Of course, there are more advanced techniques, but I'm not familiar with them yet.

**Comment by bbartling** [comment]
Ah Ok. Very impressive repo that you made with someone else's model!

Actually the bounding boxes aren't showing up....on my version wondering if its something I did trying put a rest API endpoint on the app.

I added in this to your code to export people count to IoT for one single rest API endpoint:

```
from flask import Flask, request, jsonify, render_template, Response
import flask
import threading

# py detect_flask.py --weights /content/Yolov7-Close-People-Counter/weights/yolov7x.pt --source 0 --no-trace

net_people_count = 0
host_name = "0.0.0.0"
port = 5000
app = Flask(__name__)
  
@app.route('/people-count') 
def get_updates_count(): 
  return jsonify(net_people_count)
```

And in the function called `count` I added in:

```
def count(classes,image):
  global net_people_count
  
  model_values=[]
  aligns=image.shape
  align_bottom=aligns[0]
  align_right=(aligns[1]/1.7 ) 

  for i, (k, v) in enumerate(classes.items()):
    a=f"{k} = {v}"

    if k == "person":
      net_people_count = v
```

In the `main` function I added in the web code and to kill the thread if the computer vision code is exited...
```
    t_webApp = threading.Thread(target=lambda: app.run(host=host_name, port=port, use_reloader=False))
    t_webApp.setDaemon(True)
    t_webApp.start()

    try:
      while True:
        
        with torch.no_grad():
            if opt.update:  # update all models (to fix SourceChangeWarning)
                for opt.weights in ['yolov7.pt']:
                    detect()
                    strip_optimizer(opt.weights)
            else:
                detect()
                
    except KeyboardInterrupt:
        print("Killing Flask App Thread")
        exit(0)
```

Seems to be working pretty good....all these efforts are concept ideas for the smart building industry where the company I work for we do research as a non-profit organization. At some point in time this maybe tied into a concept idea to save energy for heating and cooling systems, lower green house gas emissions, etc...that's the type research we do.

Thanks for making a cool creation....here's a [gist ](https://gist.github.com/bbartling/e512062c01d9cc02d35f5109c8cb5d40) of what I did, if you have any suggestions let me know. Just comparing this to the pyimagesearch object tracking that only classifies every 300 frames (adjustable param) this model classify' s way better and I also like the way it runs.....it runs slower which I think is better the object tracking is way faster but it the numbers of `net_people_count` were way too "jumpy" even with quite a bit of tuning efforts on my end to be used for controlling a heating and ventilation system with, I think I can already see when plotting the data over time its better....better written code base.

![image](https://user-images.githubusercontent.com/29737117/190253311-43ab0eb6-49d1-477a-9511-42d09cf882fc.png)



Thanks again!

**Comment by bbartling** [comment]
Do you know how I could make it so that only people show up in bounding boxes with priority? I like the count shown for dining table, chairs, bottle, but I think only people bounding boxes would be nice.

I'm not really sure why the other bounding boxes aren't showing up as I don't think I touched any of that code:
![image](https://user-images.githubusercontent.com/29737117/190254363-a1989b8f-d926-4228-bef7-19a710b70d48.png)

**Comment by DoganK01** [comment]
if cls == 0:

You can put the plotbox function inside the if by writing "if" code.

**Comment by bbartling** [comment]
Okay I have that thrown in as well on the plotbox function:

```
def plot_box (image,m,j,founded_people,color=(0,0,225),line_thickness=3):
  if cls == 0:
    tl = line_thickness or round(0.002 * (image.shape[0] + image.shape[1]) / 2) + 1
    c1, c2= (int(founded_people[m][0]), int(founded_people[m][3])),(int(founded_people[m][2]), int(founded_people[m][3]))
    k1, k2= (int(founded_people[j][0]), int(founded_people[j][3])),(int(founded_people[j][2]), int(founded_people[j][3]))
    cv2.rectangle(image, c1, c2, color, thickness=tl, lineType=cv2.LINE_AA)
    cv2.rectangle(image, k1, k2, color, thickness=tl, lineType=cv2.LINE_AA)
```

**Comment by bbartling** [comment]
I never worked with pytorch before....but a little bit with Keras.

Is this a pytorch process of downloading the model weights:

`wget -P /content/YOLOV7-OBJECT-COUNTER-V1.2/weights https://github.com/WongKinYiu/yolov7/releases/download/v0.1/yolov7.pt`

And then upgrading the ymal on the next step in the repo:
`pip install --upgrade pyyaml==5.3.1`

Can the model just be saved in the repo to folder without the `wget` process?

**Comment by bbartling** [comment]
For what its worth on my fork I made a `detect_flask.py` that is the complete script to output a rest endpoint on a web app for people count and to view the video feed through the browser which works well for me on remote deployments:
https://github.com/bbartling/YOLOV7-OBJECT-COUNTER-V1.2/blob/main/detect_flask.py

This computer vision code works REALLY GOOD! Way better than what I had especially when classifying people from side & back angles as well as when a person is only partially in the video frame:

![image](https://user-images.githubusercontent.com/29737117/190725171-47df2aab-f926-4e65-b36a-1a76db152f35.png)

**Comment by DoganK01** [comment]
@bbartling 
I am sorry for the delay. I'm pretty busy these days. What I meant by plot box function was not the function I wrote. It was the plot box function of the yolo model that was in the utils.py file.

As for the other problem, wget is getting the required weights. I am not training a custom data. I'm using weights that have already been trained and have the "people" class in them. If we were to train with a custom dataset, we wouldn't need to use wget. However, there are no weights in the repo that I provide and that the yolo itself provides. That's why you have to get it.

**Comment by DoganK01** [comment]
@bbartling 
Wow, you did a really good job. I'm glad it worked :).

**Comment by bbartling** [comment]
Feel free to merge it into your main repo if anyone else wants to use it as
well.

I've never done a merge before so not familiar with that step. There is
also a "templates" directory for the Flask App on html file too

**Comment by DoganK01** [comment]
@bbartling If it worked for you and if you want, I would be very happy if you could share my project :)

**Comment by bbartling** [comment]
Well it be published in a report to IEEE where our work for a project goes
through 2023 spring occupancy counting technology. We are also testing an
experimental WiFi access point system that counts people too.

Do people usually do a git merge? I never done that before on forming
something and merging it into the original authors repo....only if you want.

**Comment by DoganK01** [comment]
@bbartling As you wish. It doesn't matter much to me.

**Comment by bbartling** [comment]
Someone else asked me a question if the model can classify weapons? Like assault rifles, etc...?

**Comment by DoganK01** [comment]
If we have enough images(dataset), we can classify anything. But I guess the current model doesn't classify guns.

**Comment by bbartling** [comment]
Any chance can you give me a little more detail on how to implement that?
What function or line? Thank you.
