### ISSUE TITLE
weapons on detect.py

### ISSUE THREAD

**Issue by bbartling** [DoganK01/YOLOV7-OBJECT-COUNTER-V1.2#2]
Is it possible to add in weapons to the model? Or would one of the models do weapons? I downloaded 4 images from a Google search:

`py detect.py --weights /content/Yolov7-Close-People-Counter/weights/yolov7x.pt --source C:\Users\Administrator\Desktop\YOLOV7-OBJECT-COUNTER-V1.2\inference\images\gun1.PNG --no-trace`

![image](https://user-images.githubusercontent.com/29737117/190911440-f56be7f1-a4b4-456c-a0d7-be7404b714d2.png)

![image](https://user-images.githubusercontent.com/29737117/190911490-6dea29f9-d627-45ac-8136-de22715f9d31.png)

![image](https://user-images.githubusercontent.com/29737117/190911529-c321c7c4-1581-444f-af9b-116964caee04.png)

![image](https://user-images.githubusercontent.com/29737117/190911566-15c4d9ea-f4ba-4ccd-b869-bf4edb1fc509.png)

**Comment by DoganK01** [comment]
No, I mean it is necessary to train the model with images. After that you can classify the weapons.

**Comment by bbartling** [comment]
Are the datasets public to train a model? For example if the model I am using works really well how could I add to it?

**Comment by DoganK01** [comment]
You must either find or create your own datasets. By datasets I mean at least 1k different images for each class.

You can find the solution to the question of how to train your own model from the link below:

https://www.youtube.com/watch?v=kbMfgVZn05U&list=PL_Nji0JOuXg2QMohGK7wfzgJ-MavzXRHW&index=4
